# Generated by Django 3.2.4 on 2021-06-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('User_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255)),
                ('FName', models.CharField(blank=True, max_length=255)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Password', models.CharField(blank=True, max_length=255)),
                ('IsTeacher', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Class_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('PlaylistId', models.CharField(blank=True, max_length=255)),
                ('Cetegorie', models.CharField(blank=True, max_length=255)),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.teacherstudent')),
            ],
        ),
    ]
