# Generated by Django 3.2.4 on 2021-06-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudent',
            name='Passwords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
