# Generated by Django 3.2.4 on 2021-06-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_teacherstudent_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherstudent',
            name='Passwords',
        ),
    ]
