# Generated by Django 3.2.4 on 2021-06-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_teacherstudent_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudent',
            name='Email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
