# Generated by Django 3.2.4 on 2021-06-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_teacherstudent_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherstudent',
            old_name='User_id',
            new_name='UserId',
        ),
    ]
