# Generated by Django 3.2.4 on 2021-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_id_teacherstudent_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudent',
            name='UserId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
