# Generated by Django 3.2.4 on 2021-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_teacherstudent_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
