# Generated by Django 3.2.4 on 2021-06-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_teacherstudent_channelid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherstudent',
            name='ChannelId',
        ),
    ]
