# Generated by Django 3.2.4 on 2021-06-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_teacherstudent_channelid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherstudent',
            old_name='UserId',
            new_name='User_Id',
        ),
    ]
