# Generated by Django 3.2.4 on 2021-07-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_teacherstudent_channelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.teacherstudent'),
        ),
    ]
