# Generated by Django 3.2.4 on 2021-07-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_courses_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Cetegorie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
