# Generated by Django 3.2.4 on 2021-07-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_courses_cetegorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='Cetegorie',
        ),
        migrations.AddField(
            model_name='courses',
            name='categorie',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
