# Generated by Django 3.2.4 on 2021-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210702_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='categorie',
            field=models.CharField(max_length=255),
        ),
    ]
